# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
 repositories:
  - repository: tools
    type: git
    name: Shared%20Modules/Pipeline.Tools
  - repository: fcc
    type: github
    endpoint: A-Digital-Solution
    name: finkinfridom/food-cost-calculator

variables:
- name: sourcesDirectory
  value: $(Build.SourcesDirectory)
- name: workspace
  value: $(Pipeline.Workspace)
steps:
- checkout: self
- checkout: tools
- checkout: fcc
- script: |
    echo sourcesDirectory: $(sourcesDirectory)
    echo workspace: $(workspace)
  displayName: 'echo variables'
